# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t3nuKTG1X9tVkOY7Zrb-LGcMfjc5EYVW
"""

import numpy as np
import pandas as pd
import seaborn as sea
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Batsman_Data.csv")

df.head()

df.tail()

df.shape

df.size

df.dtypes

df.nunique()

df.columns

df.info()

df.describe()

df.describe(include = "all")

df.isnull().sum()

plt.figure(figsize=(15,15))
sea.countplot(x='Ground',data=df)
plt.show()

plt.figure(figsize=(15,15))
sea.countplot(x='Batsman',data=df)
plt.show()

plt.figure(figsize=(15,15))
sea.countplot(x='Runs',data=df)
plt.show()

from seaborn import heatmap
heatmap(data=df.corr(),annot=True)
plt.show()

sea.regplot(x=df['BF'],y=df['Runs'],data=df)
plt.show()

df = df.drop(['Bat1','BF','SR','4s','6s','Start Date','Match_ID','Player_ID'],axis = 1)

df.head()

df = df.drop('Unnamed: 0',axis=1)

df.head()

X= df.drop(['Runs'],axis=1)
Y = df['Runs']

from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
df['Batsman']= label_encoder.fit_transform(df['Batsman'])
df['Batsman'].unique()

label_encoder = preprocessing.LabelEncoder()
df['Ground']= label_encoder.fit_transform(df['Ground'])
df['Ground'].unique()

label_encoder = preprocessing.LabelEncoder()
df['Opposition']= label_encoder.fit_transform(df['Opposition'])
df['Opposition'].unique()

label_encoder = preprocessing.LabelEncoder()
df['Runs']= label_encoder.fit_transform(df['Runs'])
df['Runs'].unique()

from sklearn.model_selection import train_test_split

train_X, test_X, train_Y,test_Y = train_test_split(X, Y, test_size=0.20, random_state=42)

from sklearn.ensemble import RandomForestRegressor
fors = RandomForestRegressor()
fors.fit(test_X,test_Y)

fors=fors.score(test_X,test_Y)
comp['fors']=fors

fors.score(test_X,test_Y)